import { FileText, Download, Clock, Loader } from 'lucide-react';
import { useApp } from '../context/AppContext';

const Reports = () => {
  const { reports } = useApp();

  const formatDate = (date: Date) => {
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).format(date);
  };

  const handleDownload = (reportId: string) => {
    const report = reports.find(r => r.id === reportId);
    if (!report) return;

    const content = `
PHARMACEUTICAL RESEARCH REPORT
Generated: ${formatDate(report.generatedAt)}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

QUERY
${report.title}

EXECUTIVE SUMMARY
${report.summary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report was generated by Pharma AI Discovery Platform
All data aggregated from multiple authoritative sources including:
- IQVIA Market Intelligence
- ClinicalTrials.gov
- USPTO Patent Database
- Scientific Literature Databases
- Trade Data Sources

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pharma-ai-report-${reportId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Reports</h1>
        <p className="text-slate-600">Download and review generated research reports</p>
      </div>

      {reports.length === 0 ? (
        <div className="text-center py-16">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-slate-100 rounded-2xl mb-4">
            <FileText size={32} className="text-slate-400" />
          </div>
          <h3 className="text-lg font-semibold text-slate-900 mb-2">No reports yet</h3>
          <p className="text-slate-600">Complete a query to generate your first report</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {reports.map(report => (
            <div
              key={report.id}
              className="bg-white border border-slate-200 rounded-xl overflow-hidden hover:shadow-lg transition-shadow"
            >
              <div className="p-6">
                <div className="flex items-start justify-between mb-4">
                  <div className="p-3 bg-blue-100 rounded-lg">
                    <FileText size={24} className="text-blue-600" />
                  </div>
                  {report.status === 'generating' ? (
                    <span className="px-2 py-1 bg-yellow-100 text-yellow-700 text-xs font-medium rounded-full flex items-center gap-1">
                      <Loader size={12} className="animate-spin" />
                      Generating
                    </span>
                  ) : (
                    <span className="px-2 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-full">
                      Ready
                    </span>
                  )}
                </div>

                <h3 className="font-semibold text-slate-900 mb-2 line-clamp-2">{report.title}</h3>

                <p className="text-sm text-slate-600 mb-4 line-clamp-3">{report.summary}</p>

                <div className="flex items-center gap-2 text-xs text-slate-500 mb-4">
                  <Clock size={12} />
                  <span>{formatDate(report.generatedAt)}</span>
                </div>

                {report.status === 'ready' && (
                  <button
                    onClick={() => handleDownload(report.id)}
                    className="w-full py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 text-sm font-medium"
                  >
                    <Download size={16} />
                    Download Report
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Reports;
